
[window]
startup_mode = "SimpleFullscreen"

[scrolling]
history = 100000

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
bold   = { family = "JetBrains Mono", style = "Bold" }
italic = { family = "JetBrains Mono", style = "Italic" }
size = 17.1
offset = { y = 1 }
glyph_offset = { y = 1 }

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 700
unfocused_hollow = true

[general]
live_config_reload = true
import = [
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

